social_appp/Login/urls.py
from django.urls import path
from Login import views

app_name = "Login"

urlpatterns = [
    path('signup/',views.SignUp,name='signup'),
    path('login/',views.Login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>',views.follow,name='follow'),
    path('unfollow/<username>',views.unfollow,name='unfollow')
    
]

social_appp/social_appp/urls.py
from django.contrib import admin
from django.urls import path, include
from Social import views

# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login.urls')),
    path('post/', include('Social.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_appp/Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE,related_name='user_profile')
    profile_pic = models.ImageField(upload_to = 'profile_pictures',blank=True)
    date_of_birth = models.DateField(blank=True,null=True)
    website = models.URLField(blank=True)



class Follow(models.Model):
    follower = models.ForeignKey(User,on_delete=models.CASCADE,related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE,related_name='following')
    created_date = models.DateTimeField(auto_now_add = True)

social_appp/Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import  User
from Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm


class CreateUser(UserCreationForm):
    email = forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields =('username','email','password1','password2')

class SignIn(AuthenticationForm):
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

class EditProfile(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))
    class Meta:
        model = UserProfile
        exclude = ('user',)

social_appp/Login/views.py
from django.shortcuts import render,HttpResponseRedirect
from Login.forms import CreateUser, EditProfile, SignIn
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse,reverse_lazy
from Login.models import UserProfile , Follow
from django.contrib.auth.decorators import login_required
from Social.forms import Post_form
from django.contrib.auth.models import  User

# For User registration

def SignUp(request):
    form = CreateUser()
    registered = False
    if request.method == 'POST':
        form = CreateUser(data = request.POST)

        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('Login:login'))

    return render(request,'Login/signup.html',context={'title':'Sign Up','form':form})

# for login

def Login_page(request):
    #form = AuthenticationForm()
    form = SignIn()
    if request.method == 'POST':
        #form = AuthenticationForm(data=request.POST)
        form = SignIn(data=request.POST) 

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')


            user = authenticate(username=username,password=password)

            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('Social:home'))

    return render(request,'Login/login.html',context={'title':'Log In','form':form})

# Edit profile
@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)

    if request.method == 'POST':
        form = EditProfile(request.POST,request.FILES,instance=current_user)

        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('Social:home'))

    return render(request,'Login/profile.html',context={'form':form,'title':'Edit profile'})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login:login'))


@login_required

def Profile(request):
    form = Post_form()

    if request.method =='POST':
        form = Post_form(request.POST,request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            return HttpResponseRedirect(reverse('Social:home'))


    return render(request,'Login/user.html',context={'title':'Profile','form':form})


@login_required
def user(request,username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('Login:profile'))
    
    return render(request,'Login/user_public.html',context={'user_other':user_other,'already_followed':already_followed})

@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user

    already_followed = Follow.objects.filter(follower = follower_user, following= following_user)

    if not already_followed:
        followed_user = Follow(follower= follower_user,following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('Login:user',kwargs={'username':username}))


@login_required
def unfollow(request,username):
    following_user = User.objects.get(username=username)
    follower_user = request.user

    already_followed = Follow.objects.filter(follower = follower_user, following= following_user)
    already_followed.delete()

    return HttpResponseRedirect(reverse('Login:user',kwargs={'username':username}))

social_appp/templates/Login/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}

{% block body %}
<center>
  <div style="width:500px; border: 1px solid #ccc; padding: 100px;">
    <h3>Log In Here</h3>

    <form method="POST">
      {{form|crispy}}
      {% csrf_token %}

      <button type="submit" class="btn btn-primary" style="width:100%;">Log In</button>

    </form>

  </div>

  <div style="width:500px;border:20px #ccc;padding: 20px;">
    <p style="font-family:bold; font-size: 20px"> Don't have a account? <a href="{% url 'Login:signup' %}">Register here</a></p>

  </div>
</center>
{% endblock %}

social_appp/templates/Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}

{% block title %} {{title}}{% endblock %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy}}
    {% csrf_token %}

    <button type="submit" class="btn btn-primary" >Submit</button>

</form>

{% endblock %}

social_appp/templates/Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{title}} {% endblock %}
{% block body %}
<center>

  <div style="width:500px; border: 1px solid #ccc; padding: 40px;">
    <h4 style="font-family:bold;">Sign Up to See your photos</h4>
    <form method="POST">
      
      {% csrf_token %}
      <div class="row">
        <div class="col-6">
          {{ form.username|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.email|as_crispy_field }}
        </div>
      </div>
      {{ form.password1|as_crispy_field }}
      {{ form.password2|as_crispy_field }}

      <button type="submit" style="width:100%" class="btn btn-primary">Sign Up</button>

    </form>

  </div>

  <div style="width:500px;border:20px #ccc;padding: 20px;">
    <p style="font-family:bold; font-size: 20px">Have a account? <a href="{% url 'Login:login' %}">Log In</a></p>

  </div>
</center>


{% endblock %}

social_appp/templates/Login/user.html
{% extends 'navbar.html' %}

{% block title %} @{{user.username}}{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-4">

        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">
        {% else %}
        <img src="/media/default.png" width="250px" height="250px" class="rounded-circle">
        {% endif %}
    </div>

    <div class="col-sm-8">
        <h1>{{ user.username}} &nbsp; <a href="{% url 'Login:edit'%}" class="btn btn-light">Edit Profile</a></h1>
        <br>

        <h3>{{user.post.count}} posts &nbsp; &nbsp; {{user.following.count}} followers &nbsp; &nbsp; {{user.follower.count}} following</h3>

    </div>
</div>
<hr>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Post
  </button>

  <!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Post a Image</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body">
            <form method="POST" enctype="multipart/form-data">
                {{form.as_p}}
                {% csrf_token %}

                <button type="submit">POST</button>

            </form>
        </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
  
      </div>
    </div>
  </div>
  
  <div class="row">
    {% for post in user.post.all %}
    <img src="/media/{{post.image}}" style="width: 250px;height: 250px; overflow: hidden; padding: 20px;">

    {% endfor %}

  </div>

  
  

{% endblock %}

social_appp/templates/Login/user_public.html
{% extends 'navbar.html' %}

{% block title %} @{{user.username}}{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-4">

        {% if user_other.user_profile.profile_pic %}
        <img src="/media/{{user_other.user_profile.profile_pic}}" style=" width:250px; height:250px; class:rounded-circle;">
        {% else %}
        <img src="/media/profile_pic.png" style=" width:250px; height:250px; class:rounded-circle;">
        {% endif %}
    </div>

    <div class="col-sm-8">
        <h1>{{ user_other.username}} &nbsp;
            {% if not already_followed %}
                <a href="{% url 'Login:follow' username=user_other.username %}" class="btn btn-primary">Follow</a>
            {% else %}
                <a href="{% url 'Login:unfollow' username=user_other.username %}" class="btn btn-primary">Unfollow</a>
            {% endif %}
        
        
        </h1>
        <br>

        <h3>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} followers &nbsp; &nbsp; {{user_other.follower.count}} following</h3>

    </div>
</div>
<hr>

<div class="row">
    {% for post in user_other.post.all %}
    <img src="/media/{{post.image}}" style="width: 250px;height: 250px; overflow: hidden; padding: 20px;">

    {% endfor %}

  </div>




{% endblock %}