social_appp/Login/urls.py
from django.urls import path
from Login import views

app_name = "Login"

urlpatterns = [
    path('signup/',views.SignUp,name='signup'),
    path('login/',views.Login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>',views.follow,name='follow'),
    path('unfollow/<username>',views.unfollow,name='unfollow')
    
]

social_appp/Social/urls.py
from django.urls import path
from Social import views

app_name = "Social"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('liked/<pk>',views.liked_post,name='liked'),
    path('unliked/<pk>',views.unliked_post,name='unliked')

]

social_appp/social_appp/urls.py
from django.contrib import admin
from django.urls import path, include
from Social import views

# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login.urls')),
    path('post/', include('Social.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_appp/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <title>{% block title %}Social{% endblock %}</title>

</head>

<body>

  <div class="container" style="padding-top:20px;">
    {% block body %}
    {% endblock %}

  </div>

</body>

</html>

social_appp/templates/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <!--For font-->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <title>{% block title %}Social{% endblock %}</title>

</head>

<body>
  <nav class="navbar navbar-expand-sm bg-light navbar-light">
    <ul class="navbar nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'Social:home'%}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Login:logout' %}">LogOut</a>
        </li>
        &nbsp; &nbsp; &nbsp;
        <form class="form-inline" method="GET">
          <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
        <li class="nav-item">
          {% if user.user_profile.profile_pic%}
          <a class="nav-link" href="{% url 'Login:profile'%}"><img src="/media/{{ user.user_profile.profile_pic}}" width="40px" height="40px" 
            class="rounded-circle"></a>
          {% else %}
          <a class="nav-link" href="{% url 'Login:profile'%}"><img src="/media/profile_pic.png" width="40px" height="40px"
             class="rounded-circle"></a>
          {% endif %}

      </li>
        
    </ul>

  </nav>

  <div class="container" style="padding-top:20px;">
    {% block body %}
    {% endblock %}

  </div>

</body>

</html>