social_appp/Login/urls.py
from django.urls import path
from Login import views

app_name = "Login"

urlpatterns = [
    path('signup/',views.SignUp,name='signup'),
    path('login/',views.Login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>',views.follow,name='follow'),
    path('unfollow/<username>',views.unfollow,name='unfollow')
    
]

social_appp/Social/urls.py
from django.urls import path
from Social import views

app_name = "Social"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('liked/<pk>',views.liked_post,name='liked'),
    path('unliked/<pk>',views.unliked_post,name='unliked')

]

social_appp/social_appp/urls.py
from django.contrib import admin
from django.urls import path, include
from Social import views

# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login.urls')),
    path('post/', include('Social.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_appp/Social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=256,blank = True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-upload_date",]
        

class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='liked_post')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {} '.format(self.user, self.post)

social_appp/Social/forms.py
from django import forms
from Social.models import  Post

class Post_form(forms.ModelForm):

    class  Meta:
        model = Post
        fields = ['image','caption']

social_appp/Social/views.py
from django.shortcuts import render ,  HttpResponse ,HttpResponseRedirect
from django.urls import  reverse
from django.contrib.auth.decorators import login_required

from Login.models import UserProfile , Follow
from django.contrib.auth.models import  User
from Social.models import Post,Like

# Create your views here.

@login_required
def home (request):

    following_list = Follow.objects.filter(follower= request.user)
    posts = Post.objects.filter(author__in = following_list.values_list('following'))

    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post',flat=True)

    if request.method == 'GET':
        search = request.GET.get('search','')
        result = User.objects.filter(username__icontains = search)

    return render(request,'Social/home.html',context={'title':'Home',"search":search,"result":result,
    'posts':posts,'liked_post_list':liked_post_list})


@login_required
def liked_post(request,pk):
    post = Post.objects.get(pk=pk)
    
    already_liked = Like.objects.filter(post=post,user=request.user)

    if not already_liked:
        liked_post = Like(post=post,user=request.user)
        liked_post.save() 
    return HttpResponseRedirect(reverse('Social:home'))

@login_required
def unliked_post (request,pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(post=post,user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Social:home'))

social_appp/templates/Social/home.html
{% extends 'navbar.html' %}

{% block title %} {{title}}{% endblock %}

{% block body %}

{% if search %}
    {% for user in result %}
        <div class="row">
            <div class="col-sm-2">
                {% if user.user_profile.profile_pic %}
                    <img src="/media/{{user.user_profile.profile_pic}}" style="width: 100px;height: 100px;" 
                    class="round-circle">                   
                {% else %}
                    <img src="/media/profile_pic.png" style="width: 100px;height: 100px;" class="round-circle">
                {% endif %}
                <hr>
            </div>
            <div class="col-sm-10">
               <a href="{% url 'Login:user' username=user.username %}">{{user.username}}</a>
            </div>
         </div>        
    {% endfor %}
    

{% else %}
        <div class="row">
            <div class="col-sm-8">               
                {% for post in posts %}
                    <div class="row" style="border: 1px solid #888888;">
                        <div style="padding: 10px;">
                            {% if post.author.user_profile.profile_pic %}
                            <img src="/media/{{post.author.user_profile.profile_pic}}" style="width: 50px;height: 50px;" 
                                class="round-circle">
                            {% else %}
                                <img src="/media/profile_pic.png" style="width: 50px;height: 50px;" class="round-circle">
                            {% endif %}
                            <a href="{% url 'Login:user' username=post.author %}">{{post.author}}</a>
                        </div>
                        <br>
                        <br>
                        {{post.caption}}<br>
                        <img src="/media/{{post.image}}" width="100%">
                        

                        <div style="padding:20px;">
                            
                            {{ post.liked_post.count }} Likes <br>
                            {% if post.pk in liked_post_list %}
                                <a href="{% url 'Social:unliked' pk=post.pk %}"><i class="fa fa-heart" style="font-size:36px;"></i></a>
                            {% else %}
                                <a href="{% url 'Social:liked' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size:36px;"></i></a>
                            {% endif %}

                        </div>
                    </div>
                    <br>
                    <br>
                    
                {% endfor %}
            </div>

            <div class="col-sm-4">
                <div class="row">
                    <div class="col-sm-4">

                        {% if user.user_profile.profile_pic %}
                            <img src="/media/{{user.user_profile.profile_pic}}" style="width: 100px;height: 100px;" 
                            class="round-circle">
                    

                        {% else %}
                            <img src="/media/profile_pic.png" style="width: 100px;height: 100px;" class="round-circle">
                    

                        {% endif %}


                    </div>
                    <div class="col-sm-8">
                        {{user.username}}

                    </div>

                </div>

            </div>


        </div>


   

{% endif %}

{% endblock %}